### ISSUE TITLE
GTA:SA is grouped in "Installed", but it is not

### ISSUE THREAD

**Issue by LukasThyWalls** [tylerbrawl/Galaxy-Plugin-Rockstar#108]
Hello

I only have GTA:SA in my Rockstar account, and i detected GOG Galaxy group it in "Installed" games in "Owned Games" and "Rockstar" Bookmarks, but it is not, and i never installled in this machine. The weird thing is in the "Installed" bookmark it doesn't appear, and always the option when i right click or click on it is to install.

My Rockstar plugin log file:
```
2020-05-06 19:41:25,080 - root - DEBUG - Using proactor: IocpProactor
2020-05-06 19:41:25,097 - galaxy.api.plugin - INFO - Using local address: 127.0.0.1:61123
2020-05-06 19:41:25,097 - galaxy.api.plugin - INFO - Creating plugin for platform rockstar, version 0.5.4
2020-05-06 19:41:25,100 - root - DEBUG - ROCKSTAR_INSTALLER_PATH: ***
2020-05-06 19:41:25,131 - galaxy.api.jsonrpc - DEBUG - Received 66 bytes of data
2020-05-06 19:41:25,132 - galaxy.api.jsonrpc - INFO - Handling request: id=0, method=get_capabilities, params={}
2020-05-06 19:41:25,133 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "rockstar", "features": ["ImportInstalledGames", "ImportAchievements", "LaunchGame", "ImportFriends", "ImportUserPresence", "LaunchPlatformClient", "InstallGame", "ImportOwnedGames", "ShutdownPlatformClient", "UninstallGame", "ImportGameTime"], "token": "8f03792c-2155-4483-b0f4-de812a5249ae"}}
2020-05-06 19:41:25,410 - galaxy.api.jsonrpc - DEBUG - Received 30853 bytes of data
2020-05-06 19:41:25,411 - galaxy.api.jsonrpc - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
2020-05-06 19:41:25,411 - galaxy.task_manager - DEBUG - Task manager plugin internal: creating task 0 (tick)
2020-05-06 19:41:25,412 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2020-05-06 19:41:25,509 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2020-05-06 19:41:25,510 - galaxy.api.jsonrpc - INFO - Handling request: id=2, method=ping, params={}
2020-05-06 19:41:25,510 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "2", "result": null}
2020-05-06 19:41:26,066 - galaxy.api.jsonrpc - DEBUG - Received 30511 bytes of data
2020-05-06 19:41:26,067 - galaxy.api.jsonrpc - INFO - Handling request: id=3, method=init_authentication, params={'stored_credentials': '****'}
2020-05-06 19:41:26,067 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 0 (init_authentication)
2020-05-06 19:41:26,067 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 0 (init_authentication)
2020-05-06 19:41:26,123 - root - INFO - INFO: The credentials were successfully obtained.
2020-05-06 19:41:26,124 - root - INFO - INFO: The stored credentials were successfully parsed. Beginning authentication...
2020-05-06 19:41:26,124 - root - DEBUG - ROCKSTAR_SC_BEARER_OLD: eyJhb***3zA
2020-05-06 19:41:27,568 - root - DEBUG - ROCKSTAR_SC_TS01a305c4: ***
2020-05-06 19:41:28,263 - root - DEBUG - ROCKSTAR_SC_BEARER_NEW: eyJhb***J_w
2020-05-06 19:41:28,263 - root - DEBUG - ROCKSTAR_SC_REFRESH_SUCCESS: The Social Club user has been successfully re-authenticated!
2020-05-06 19:41:28,263 - root - DEBUG - ROCKSTAR_OLD_AUTH: Q2FrZ***%3D
2020-05-06 19:41:29,134 - root - DEBUG - ROCKSTAR_NEW_TS_COOKIE: ***
2020-05-06 19:41:29,134 - root - DEBUG - ROCKSTAR_NEW_AUTH: Q2FrZ***%3D
2020-05-06 19:41:29,135 - root - DEBUG - ROCKSTAR_HTTP_CHECK: Got bearer token: eyJhb***3IQ
2020-05-06 19:41:29,839 - root - DEBUG - ROCKSTAR_HTTP_CHECK: Got display name: L*** / Got Rockstar ID: ***
2020-05-06 19:41:29,840 - root - DEBUG - ROCKSTAR_STORE_CREDENTIALS: Preparing to store credentials...
2020-05-06 19:41:29,864 - galaxy.api.jsonrpc - INFO - Sending notification: method=store_credentials, params={'display_name': '****', 'rockstar_id': '****', 'cookie_jar': '****', 'current_auth_token': '****', 'current_sc_token': '****', 'refresh_token': '****', 'fingerprint': '****'}
2020-05-06 19:41:29,865 - galaxy.api.jsonrpc - DEBUG - Sending 30512 bytes of data
2020-05-06 19:41:29,865 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 0 (init_authentication)
2020-05-06 19:41:29,866 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "3", "result": {"user_id": "139579365", "user_name": "LukasThyWalls"}}
2020-05-06 19:41:29,866 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 0 (init_authentication)
2020-05-06 19:41:30,422 - root - DEBUG - Checking for new games...
2020-05-06 19:41:30,423 - root - DEBUG - Checking local game statuses...
2020-05-06 19:41:30,523 - galaxy.api.jsonrpc - DEBUG - Received 54 bytes of data
2020-05-06 19:41:30,523 - galaxy.api.jsonrpc - INFO - Handling request: id=4, method=ping, params={}
2020-05-06 19:41:30,523 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "4", "result": null}
2020-05-06 19:41:30,976 - galaxy.api.jsonrpc - DEBUG - Received 68 bytes of data
2020-05-06 19:41:30,976 - galaxy.api.jsonrpc - INFO - Handling request: id=5, method=import_owned_games, params={}
2020-05-06 19:41:30,977 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 1 (import_owned_games)
2020-05-06 19:41:30,977 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 1 (import_owned_games)
2020-05-06 19:41:30,977 - galaxy.api.jsonrpc - DEBUG - Received 68 bytes of data
2020-05-06 19:41:30,977 - galaxy.api.jsonrpc - INFO - Handling request: id=6, method=import_local_games, params={}
2020-05-06 19:41:30,978 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 2 (import_local_games)
2020-05-06 19:41:30,978 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:30,994 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:30,996 - root - ERROR - ROCKSTAR_LOG_FINISHED_ERROR: The entire log file was read, but all of the games could not be accounted for. Proceeding to import the games that have been confirmed...
2020-05-06 19:41:30,996 - root - WARNING - ROCKSTAR_LOG_WARNING: There are no owned games listed in D:\Apps\AppData\Rockstar Games\Launcher\launcher.log. Moving to the next log file...
2020-05-06 19:41:30,997 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:31,002 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:31,005 - root - ERROR - ROCKSTAR_LOG_FINISHED_ERROR: The entire log file was read, but all of the games could not be accounted for. Proceeding to import the games that have been confirmed...
2020-05-06 19:41:31,005 - root - WARNING - ROCKSTAR_LOG_WARNING: There are no owned games listed in D:\Apps\AppData\Rockstar Games\Launcher\launcher.01.log. Moving to the next log file...
2020-05-06 19:41:31,005 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:31,015 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:31,017 - root - DEBUG - ROCKSTAR_ADD_GAME: Adding gtasa to owned games cache...
2020-05-06 19:41:31,018 - galaxy.api.jsonrpc - INFO - Sending notification: method=owned_game_added, params={'owned_game': Game(game_id='18', game_title='Grand Theft Auto: San Andreas', dlcs=None, license_info=LicenseInfo(license_type=<LicenseType.SinglePurchase: 'SinglePurchase'>, owner=None))}
2020-05-06 19:41:31,018 - galaxy.api.jsonrpc - DEBUG - Sending 193 bytes of data
2020-05-06 19:41:31,018 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 1 (import_owned_games)
2020-05-06 19:41:31,019 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 2 (import_local_games)
2020-05-06 19:41:31,019 - galaxy.api.jsonrpc - DEBUG - Received 64 bytes of data
2020-05-06 19:41:31,019 - galaxy.api.jsonrpc - INFO - Handling request: id=7, method=import_friends, params={}
2020-05-06 19:41:31,020 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 3 (import_friends)
2020-05-06 19:41:31,020 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "5", "result": {"owned_games": [{"game_id": "18", "game_title": "Grand Theft Auto: San Andreas", "license_info": {"license_type": "SinglePurchase"}}]}}
2020-05-06 19:41:31,021 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 1 (import_owned_games)
2020-05-06 19:41:31,022 - root - DEBUG - ROCKSTAR_INSTALLED_GAMES: {'launcher': LocalGame(game_id='21', local_game_state=<LocalGameState.Installed: 1>), 'gtasa': LocalGame(game_id='18', local_game_state=<LocalGameState.None_: 0>), 'gta5': LocalGame(game_id='11', local_game_state=<LocalGameState.None_: 0>), 'lanoire': LocalGame(game_id='9', local_game_state=<LocalGameState.None_: 0>), 'mp3': LocalGame(game_id='10', local_game_state=<LocalGameState.None_: 0>), 'gta3': LocalGame(game_id='26', local_game_state=<LocalGameState.None_: 0>), 'gtavc': LocalGame(game_id='27', local_game_state=<LocalGameState.None_: 0>), 'bully': LocalGame(game_id='23', local_game_state=<LocalGameState.None_: 0>), 'rdr2': LocalGame(game_id='13', local_game_state=<LocalGameState.None_: 0>), 'gta4': LocalGame(game_id='1', local_game_state=<LocalGameState.None_: 0>)}
2020-05-06 19:41:31,022 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 2 (import_local_games)
2020-05-06 19:41:31,023 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 3 (import_friends)
2020-05-06 19:41:31,024 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "6", "result": {"local_games": [{"game_id": "21", "local_game_state": 1}, {"game_id": "18", "local_game_state": 0}, {"game_id": "11", "local_game_state": 0}, {"game_id": "9", "local_game_state": 0}, {"game_id": "10", "local_game_state": 0}, {"game_id": "26", "local_game_state": 0}, {"game_id": "27", "local_game_state": 0}, {"game_id": "23", "local_game_state": 0}, {"game_id": "13", "local_game_state": 0}, {"game_id": "1", "local_game_state": 0}]}}
2020-05-06 19:41:31,024 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 2 (import_local_games)
2020-05-06 19:41:31,156 - root - DEBUG - ROCKSTAR_FRIENDS_REQUEST: ***
2020-05-06 19:41:31,157 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 3 (import_friends)
2020-05-06 19:41:31,157 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "7", "result": {"friend_info_list": []}}
2020-05-06 19:41:31,158 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 3 (import_friends)
2020-05-06 19:41:31,478 - galaxy.api.jsonrpc - DEBUG - Received 92 bytes of data
2020-05-06 19:41:31,478 - galaxy.api.jsonrpc - INFO - Handling request: id=8, method=start_achievements_import, params={'game_ids': ['18']}
2020-05-06 19:41:31,478 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 4 (start_achievements_import)
2020-05-06 19:41:31,479 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 4 (start_achievements_import)
2020-05-06 19:41:31,479 - galaxy.api.jsonrpc - DEBUG - Received 90 bytes of data
2020-05-06 19:41:31,480 - galaxy.api.jsonrpc - INFO - Handling request: id=9, method=start_game_times_import, params={'game_ids': ['18']}
2020-05-06 19:41:31,480 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 5 (start_game_times_import)
2020-05-06 19:41:31,480 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 5 (achievements import)
2020-05-06 19:41:31,480 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 4 (start_achievements_import)
2020-05-06 19:41:31,481 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 6 (start_game_times_import)
2020-05-06 19:41:31,481 - galaxy.api.jsonrpc - DEBUG - Received 93 bytes of data
2020-05-06 19:41:31,481 - galaxy.api.jsonrpc - INFO - Handling request: id=10, method=start_achievements_import, params={'game_ids': ['18']}
2020-05-06 19:41:31,482 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 6 (start_achievements_import)
2020-05-06 19:41:31,482 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "8", "result": null}
2020-05-06 19:41:31,482 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 4 (start_achievements_import)
2020-05-06 19:41:31,483 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 7 (game times import)
2020-05-06 19:41:31,483 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 6 (start_game_times_import)
2020-05-06 19:41:31,483 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 8 (start_achievements_import)
2020-05-06 19:41:31,484 - galaxy.api.jsonrpc - DEBUG - Received 91 bytes of data
2020-05-06 19:41:31,484 - galaxy.api.jsonrpc - INFO - Handling request: id=11, method=start_game_times_import, params={'game_ids': ['18']}
2020-05-06 19:41:31,484 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 7 (start_game_times_import)
2020-05-06 19:41:31,484 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '18', 'unlocked_achievements': []}
2020-05-06 19:41:31,485 - galaxy.api.jsonrpc - DEBUG - Sending 123 bytes of data
2020-05-06 19:41:31,485 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "9", "result": null}
2020-05-06 19:41:31,486 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 5 (start_game_times_import)
2020-05-06 19:41:31,486 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 9 (start_game_times_import)
2020-05-06 19:41:31,486 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_time_import_success, params={'game_time': GameTime(game_id='18', time_played=None, last_played_time=None)}
2020-05-06 19:41:31,487 - galaxy.api.jsonrpc - DEBUG - Sending 101 bytes of data
2020-05-06 19:41:31,487 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "10", "error": {"code": 600, "message": "Import already in progress"}}
2020-05-06 19:41:31,487 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 6 (start_achievements_import)
2020-05-06 19:41:31,488 - galaxy.api.jsonrpc - INFO - Sending notification: method=achievements_import_finished, params=None
2020-05-06 19:41:31,488 - galaxy.api.jsonrpc - DEBUG - Sending 77 bytes of data
2020-05-06 19:41:31,488 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 5 (achievements import)
2020-05-06 19:41:31,489 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "11", "error": {"code": 600, "message": "Import already in progress"}}
2020-05-06 19:41:31,489 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 7 (start_game_times_import)
2020-05-06 19:41:31,489 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_times_import_finished, params=None
2020-05-06 19:41:31,490 - galaxy.api.jsonrpc - DEBUG - Sending 75 bytes of data
2020-05-06 19:41:31,490 - root - DEBUG - ROCKSTAR_GAME_TIME: Pushing the cache of played game times to the persistent cache...
2020-05-06 19:41:31,490 - galaxy.api.jsonrpc - INFO - Sending notification: method=push_cache, params={'data': '****'}
2020-05-06 19:41:31,491 - galaxy.api.jsonrpc - DEBUG - Sending 30679 bytes of data
2020-05-06 19:41:31,491 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 7 (game times import)
2020-05-06 19:41:32,732 - root - WARNING - ROCKSTAR_SC_LIGHT_REFRESH_FAILED: The light method for refreshing the Social Club user's authentication has failed. Falling back to the strict refresh method...
2020-05-06 19:41:32,917 - root - DEBUG - ROCKSTAR_OLD_AUTH_REFRESH: Q2FrZ***%3D
2020-05-06 19:41:32,917 - root - DEBUG - ROCKSTAR_GET_COOKIE_ERROR: The cookie TS019978c2 from domain support.rockstargames.com does not exist!
2020-05-06 19:41:33,469 - root - DEBUG - ROCKSTAR_NEW_AUTH_REFRESH: Q2FrZ***%3D
2020-05-06 19:41:33,469 - root - DEBUG - ROCKSTAR_REFRESH_SUCCESS: The user has been successfully re-authenticated!
2020-05-06 19:41:33,469 - root - DEBUG - ROCKSTAR_SC_BEARER_OLD: eyJhb***J_w
2020-05-06 19:41:34,138 - root - DEBUG - ROCKSTAR_SC_TS01a305c4: ***
2020-05-06 19:41:34,445 - root - DEBUG - ROCKSTAR_SC_BEARER_NEW: eyJhb***dJw
2020-05-06 19:41:34,445 - root - DEBUG - ROCKSTAR_SC_REFRESH_SUCCESS: The Social Club user has been successfully re-authenticated!
2020-05-06 19:41:35,019 - root - ERROR - ROCKSTAR_PLAYED_GAMES_ERROR: The request to scrape the user's played games resulted in this exception: TypeError('Cannot serialize non-str key None')
Traceback (most recent call last):
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 359, in get_played_games
    resp_json = await self._get_google_tag_data()
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 353, in _get_google_tag_data
    resp = await self._current_session.get(url, headers=headers)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 502, in _request
    resp = await req.send(conn)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 629, in send
    await writer.write_headers(status_line, self.headers)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\http_writer.py", line 111, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp\_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
  File "aiohttp\_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 378, in get_played_games
    return await self.get_played_games(callback=True)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 359, in get_played_games
    resp_json = await self._get_google_tag_data()
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 353, in _get_google_tag_data
    resp = await self._current_session.get(url, headers=headers)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 502, in _request
    resp = await req.send(conn)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 629, in send
    await writer.write_headers(status_line, self.headers)
  File "C:\Users\Lukas ThyWalls\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\http_writer.py", line 111, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp\_http_writer.pyx", line 138, in aiohttp._http_writer._serialize_headers
  File "aiohttp\_http_writer.pyx", line 110, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
2020-05-06 19:41:35,170 - root - ERROR - ROCKSTAR_PLAYED_GAMES_ERROR: The exception TypeError('Cannot serialize non-str key None') was thrown when attempting to get the user's played games online. Falling back to log file check...
2020-05-06 19:41:35,170 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:35,174 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:35,177 - root - ERROR - ROCKSTAR_LOG_FINISHED_ERROR: The entire log file was read, but all of the games could not be accounted for. Proceeding to import the games that have been confirmed...
2020-05-06 19:41:35,177 - root - WARNING - ROCKSTAR_LOG_WARNING: There are no owned games listed in D:\Apps\AppData\Rockstar Games\Launcher\launcher.log. Moving to the next log file...
2020-05-06 19:41:35,177 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:35,185 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:35,187 - root - ERROR - ROCKSTAR_LOG_FINISHED_ERROR: The entire log file was read, but all of the games could not be accounted for. Proceeding to import the games that have been confirmed...
2020-05-06 19:41:35,188 - root - WARNING - ROCKSTAR_LOG_WARNING: There are no owned games listed in D:\Apps\AppData\Rockstar Games\Launcher\launcher.01.log. Moving to the next log file...
2020-05-06 19:41:35,188 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-05-06 19:41:35,191 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-05-06 19:41:35,430 - root - DEBUG - Checking local game statuses...
2020-05-06 19:41:35,606 - galaxy.api.jsonrpc - DEBUG - Received 55 bytes of data
2020-05-06 19:41:35,607 - galaxy.api.jsonrpc - INFO - Handling request: id=12, method=ping, params={}
2020-05-06 19:41:35,607 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "12", "result": null}
2020-05-06 19:41:40,436 - root - DEBUG - Checking local game statuses...
2020-05-06 19:41:40,643 - galaxy.api.jsonrpc - DEBUG - Received 55 bytes of data
2020-05-06 19:41:40,643 - galaxy.api.jsonrpc - INFO - Handling request: id=13, method=ping, params={}
2020-05-06 19:41:40,644 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "13", "result": null}
2020-05-06 19:41:45,670 - galaxy.api.jsonrpc - DEBUG - Received 55 bytes of data
2020-05-06 19:41:45,670 - galaxy.api.jsonrpc - INFO - Handling request: id=14, method=ping, params={}
2020-05-06 19:41:45,671 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "14", "result": null}
2020-05-06 19:41:46,421 - root - DEBUG - Checking local game statuses...
2020-05-06 19:41:50,677 - galaxy.api.jsonrpc - DEBUG - Received 55 bytes of data
2020-05-06 19:41:50,678 - galaxy.api.jsonrpc - INFO - Handling request: id=15, method=ping, params={}
2020-05-06 19:41:50,678 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "15", "result": null}
```

**Comment by tylerbrawl** [comment]
I'm not quite sure I understand the issue. Is the game appearing when the ``Status > Installed`` filter is enabled, despite the fact that the game is not in the "Installed" bookmark and opening the game in Galaxy prompts you to install it?

If this is the case, then it really sounds like a bug with Galaxy 2.0, and not with the plugin. In the log file you posted, the plugin is sending the correct installation status of Grand Theft Auto: San Andreas to the Galaxy client, as shown here:

```
2020-05-06 19:41:31,022 - root - DEBUG - ROCKSTAR_INSTALLED_GAMES: {'launcher': LocalGame(game_id='21', local_game_state=<LocalGameState.Installed: 1>), 'gtasa': LocalGame(game_id='18', local_game_state=<LocalGameState.None_: 0>), 'gta5': LocalGame(game_id='11', local_game_state=<LocalGameState.None_: 0>), 'lanoire': LocalGame(game_id='9', local_game_state=<LocalGameState.None_: 0>), 'mp3': LocalGame(game_id='10', local_game_state=<LocalGameState.None_: 0>), 'gta3': LocalGame(game_id='26', local_game_state=<LocalGameState.None_: 0>), 'gtavc': LocalGame(game_id='27', local_game_state=<LocalGameState.None_: 0>), 'bully': LocalGame(game_id='23', local_game_state=<LocalGameState.None_: 0>), 'rdr2': LocalGame(game_id='13', local_game_state=<LocalGameState.None_: 0>), 'gta4': LocalGame(game_id='1', local_game_state=<LocalGameState.None_: 0>)}
[. . .]
2020-05-06 19:41:31,024 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "6", "result": {"local_games": [{"game_id": "21", "local_game_state": 1}, {"game_id": "18", "local_game_state": 0}, {"game_id": "11", "local_game_state": 0}, {"game_id": "9", "local_game_state": 0}, {"game_id": "10", "local_game_state": 0}, {"game_id": "26", "local_game_state": 0}, {"game_id": "27", "local_game_state": 0}, {"game_id": "23", "local_game_state": 0}, {"game_id": "13", "local_game_state": 0}, {"game_id": "1", "local_game_state": 0}]}}
```

Unless you are certain that the problem is with this plugin, I would suggest filing a bug report on the Galaxy 2.0 client.

**Comment by LukasThyWalls** [comment]
I don't really know, but i just recently reinstalled Galaxy. The reason to reinstall was i have some issues with the integrations failing to connect when i start Galaxy, then i was using _GOG Integration Updater by Slashbunny_ and now i'm installing the integration with Galaxy itself, although i still have issues with them failing when i start Galaxy sometimes, and i'm not sure Galaxy itself is updating these non official integrations as anywhere says it does or not...

But back to the topic, in the past i have this issue with two Games: GTA:SA (Rockstar) and Theme Hospital (Origin). The issue is i don't have any game installed, less these ones, and in "Installed" inside Galaxy said no games, but when i group as Installed/Not Installed the _Rockstar_ bookmark or the _Owned Games_ bookmark, (And _Origin_ Bookmark in the case of Theme Hospital), Galaxy showed these games as Installed, when they aren't. TH was installed before and i uninstalled directly in Origin, so i thought is something with the registry or something like that, with GTA:SA i don't know i never installed it, but then decided to reinstalled Galaxy.

So, i uninstall and install Galaxy again, now using the built-in integration search to add integrations and, i logged everything and all integrations hasve fetched the games. Now, Theme Hospital is not grouped as "Installed" anywhere, so i fixed that with the reinstall, but GTA:SA still is grouped as "Installed". I have updated Rockstar Games Launcher, and Galaxy, and the integration (I installed it through Galaxy itself, searching the integration, is updated? will it update? I don't know...). In Rockstar Games Launcher is not installed.

The main issue with going directly to the Galaxy bug tracker is they will said is a problem with the integration, so i need to be sure it is not.

So, What can i do to give more info? Or made a proper reset of the integration? Am i the only one with this issue?

**Comment by tylerbrawl** [comment]
Thank you for providing additional information. As it turns out, it's not your fault. I followed the process that you described, and my games are being listed in this manner as well, despite not being installed. This means that it is definitely a problem with the integration, and not with Galaxy 2.0. I will look into the issue.

**Comment by tylerbrawl** [comment]
Actually, I take back part of what I said. The issue remains that these games are still being displayed incorrectly, but there is nothing in the API which would seem to resolve this. As such, I now believe that Galaxy 2.0 is at fault, and not the plugin. I have reported the issue on the Galaxy 2.0 client.

In the meantime, if any other individuals can give insight into this problem, it would be appreciated.

**Comment by fl4shback** [comment]
Hi!
Was looking into this issue because I hate my games being listed as installed when they are not.

After reading other plugins code, it seems that the return of the function at line https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/blob/9e6a4b63f666ce6e948c8f414b9d54e2aba44490/src/plugin.py#L608 should only contain the list of installed games. Right now it contains the list of all games with the LocalGameState parameter.

Not being a dev, I sadly can't test my theory and can't provide a PR.
If anyone has some time to test this !
