### ISSUE TITLE
Integration Offline

### ISSUE THREAD

**Issue by cderring** [tylerbrawl/Galaxy-Plugin-Rockstar#127]
Hello,
The Rockstar integration to GOG Galaxy seems to be broken.  Once you connect, it goes to "Offline Retry" and will not connect.  The connection screen has you log into the Rockstar and then the window refreshes to show Rockstar game news and then jumps back to GOG galaxy.

**Comment by FaithTheSlayer** [comment]
Mine works fine

**Comment by cderring** [comment]
Odd.  It could be just my PC and network setup, I guess.  How can I 
verify the issue or dig into a root cause?

**Comment by Mighto360** [comment]
Same thing is happening to me today, so it's not just you. From looking at the list of closed issues, it seems like Rockstar slightly changes their auth system fairly often, so maybe that's what this is.

**Comment by cderring** [comment]
Well, I'm happy to see I'm not the only one but sorry to see something 
is broke.

Anyone know if there are there logs or screen shots that we can provide 
to help get this issue resolved?

Thanks,

**Comment by BuryTomorrow12** [comment]
Same issue. Shows as offline as soon as I log in.

I'm using my google credentials to log in to Rockstar.

**Comment by NiNiyas** [comment]
Same issue.

**Comment by tylerbrawl** [comment]
I apologize for taking an embarrassingly long time to get back to you guys. I believe this error occurs when you attempt to log in without multi-factor authentication, as the plugin worked fine on my main account but failed on a test account without MFA. I just pushed a commit to `fog_release` which fixes the issue described by @NiNiyas. Eventually, the plugin will be updated automatically on Galaxy 2.0 to fix this issue.

If anybody is having an issue which is different from the one described by @NiNiyas, then please create a separate issue.

**Comment by jto-GH** [comment]
Hello,
I am also experiencing this issue. I do have multi factor authentication enabled on my Rockstar account. After signing in with email, password and authentication, the integration says Offline (retry). I did try two instances, one where I chose to remember my email/credential and this device, and another instance without remembering. In both instances, it did not connect properly.

**Comment by tylerbrawl** [comment]
You're getting the issues even with MFA enabled, @jto-GH? Maybe the issue isn't with that, after all. Regardless, if the error in your log file is the same as that in the one from @NiNiyas, then I believe my commit may have fixed your issues, anyways. (In more technical terms, I probably made a mistake in parsing cookies. I don't know why cookies with an empty name were being added in the first place, though.)

It may take some time before the update gets pushed to the Galaxy 2.0 client. If you want, you can manually install the update by downloading and installing the files from the `master` branch.

@cderring - For future reference, you can find Galaxy 2.0 plugin log files on Windows platforms by searching in ``C:\ProgramData\GOG.com\Galaxy\logs``. (I am not sure what the installation directory for Mac OS X would be.) It might help to sort the log files by date created/modified.

**Comment by mbc07** [comment]
My login credentials expired and GOG Galaxy asked to reauthenticate today. After logging in (with MFA), I get the same "Offline (retry)" message. The plugin log complains about a different error from the previously sent logs, though:

```
Traceback (most recent call last):
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 254, in _get_user_json
    r"%22%7D%7D", headers=headers, allow_redirects=False)
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 625, in _request
    resp.raise_for_status()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://www.rockstargames.com/graph.json?operationName=User&variables=%7B%22locale%22:%22en_us%22%7D&extensions=%7B%22persistedQuery%22:%7B%22version%22:1,%22sha256Hash%22:%226aa5127bff85d7fc23ffc192c74bb2e38c3c855482b33b2395aa103a554e9241%22%7D%7D')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 658, in _refresh_credentials_base
    final_request = await self._current_session.get(url, headers=headers)
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 625, in _request
    resp.raise_for_status()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://www.rockstargames.com/graph.json?operationName=User&variables=%7B%22code%22:%22462f4475-02b6-42ad-8b44-97bb61f2e37d%22,%22locale%22:%22en_us%22%7D&extensions=%7B%22persistedQuery%22:%7B%22version%22:1,%22sha256Hash%22:%226aa5127bff85d7fc23ffc192c74bb2e38c3c855482b33b2395aa103a554e9241%22%7D%7D')
2021-01-23 22:10:41,649 - root - ERROR - ROCKSTAR_USER_JSON_ERROR: The request to get the user from the graph failed even after attempting to refresh credentials. Revoking user authentication...
Traceback (most recent call last):
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 254, in _get_user_json
    r"%22%7D%7D", headers=headers, allow_redirects=False)
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 625, in _request
    resp.raise_for_status()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://www.rockstargames.com/graph.json?operationName=User&variables=%7B%22locale%22:%22en_us%22%7D&extensions=%7B%22persistedQuery%22:%7B%22version%22:1,%22sha256Hash%22:%226aa5127bff85d7fc23ffc192c74bb2e38c3c855482b33b2395aa103a554e9241%22%7D%7D')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 658, in _refresh_credentials_base
    final_request = await self._current_session.get(url, headers=headers)
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client.py", line 625, in _request
    resp.raise_for_status()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://www.rockstargames.com/graph.json?operationName=User&variables=%7B%22code%22:%22462f4475-02b6-42ad-8b44-97bb61f2e37d%22,%22locale%22:%22en_us%22%7D&extensions=%7B%22persistedQuery%22:%7B%22version%22:1,%22sha256Hash%22:%226aa5127bff85d7fc23ffc192c74bb2e38c3c855482b33b2395aa103a554e9241%22%7D%7D')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 291, in _get_user_json
    await self.refresh_credentials()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 578, in refresh_credentials
    await self._refresh_credentials_base()
  File "C:\Users\mbc07\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\http_client.py", line 676, in _refresh_credentials_base
    raise InvalidCredentials
galaxy.api.errors.InvalidCredentials
2021-01-23 22:10:41,650 - root - ERROR - ERROR: The request to refresh credentials resulted in this exception: AuthenticationRequired()
2021-01-23 22:10:41,650 - root - ERROR - InvalidCredentials()
2021-01-23 22:10:41,650 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "722", "error": {"code": 100, "message": "Invalid credentials"}}
2021-01-23 22:10:41,650 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: finished task 3 (pass_login_credentials)
```
**GOG Galaxy version:** 2.0.36
**Rockstar Plugin version:** 0.5.10
**OS:** Windows 10 Pro (build 21296)

**Comment by FaithTheSlayer** [comment]
Booted up gog galaxy today and was disconnected had to reconnect to rockstar and when i did it was offline. help!

**Comment by FaithTheSlayer** [comment]
wont stay when i turn gog off and then back on again

**Comment by tylerbrawl** [comment]
I can't believe they changed their authentication flow *again*. At this point, though, I really shouldn't be surprised. Anyways, the issue should be fixed with #136. The plugin will update automatically after some time.

**Comment by FaithTheSlayer** [comment]
> I can't believe they changed their authentication flow _again_. At this point, though, I really shouldn't be surprised. Anyways, the issue should be fixed with #136. The plugin will update automatically after some time.

How long usually is "after some time" ? Thanks!

**Comment by Moredey** [comment]
Appreciate the clarification, was wondering why it was just not working.

**Comment by FaithTheSlayer** [comment]
> I can't believe they changed their authentication flow _again_. At this point, though, I really shouldn't be surprised. Anyways, the issue should be fixed with #136. The plugin will update automatically after some time.

Where Can I find the latest so I can update manually instead of waiting for the update? Thanks!

**Comment by tylerbrawl** [comment]
Sorry for the late reply. I have gotten confirmation that the update has been merged by the FoG auto-updater, so I would think that it should be available by now. If not, then you can use the provided .zip archive to manually install it.

[Plugin (0.5.11).zip](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/5874274/Plugin.0.5.11.zip)

**Comment by Moredey** [comment]
> Sorry for the late reply. I have gotten confirmation that the update has been merged by the FoG auto-updater, so I would think that it should be available by now. If not, then you can use the provided .zip archive to manually install it.

Plugin (0.5.11).zip

That did the trick, appreciate it!

**Comment by hightower5** [comment]
Hello @tylerbrawl, 
the integration is again offline. For weeks. ;)

Best regards
Tom

**Comment by Moredey** [comment]
> Hello @tylerbrawl,
> the integration is again offline. For weeks. ;)
> 
> Best regards
> Tom

Works fine for me, try manually downloading the integration above.

**Comment by BuryTomorrow12** [comment]
Plugin doesn't even load the login window now.

![imagen_2021-03-17_133217](https://user-images.githubusercontent.com/40051760/111503083-31901d00-8725-11eb-9649-528ccc8446ce.png)

**Comment by FaithTheSlayer** [comment]
> Plugin doesn't even load the login window now.
> 
> ![imagen_2021-03-17_133217](https://user-images.githubusercontent.com/40051760/111503083-31901d00-8725-11eb-9649-528ccc8446ce.png)

Same Here

**Comment by FaithTheSlayer** [comment]
Same Here
