### ISSUE TITLE
No games listed

### ISSUE THREAD

**Issue by MateEke** [tylerbrawl/Galaxy-Plugin-Rockstar#132]
Hi!

I have installed the plugin on GOG Galaxy's integrations page ("version": "0.5.6"), succesfully connected my account - it displays "Connected (my_username)", but there aren't any games discovered. I own RDR2 and GTA:SA on Rockstar, and RDR2 is currently installed on my system.

The only error I can see in the logs:
```
2020-12-11 10:29:52,258 - galaxy.api.importer - ERROR - Unexpected exception raised in local size importer
Traceback (most recent call last):
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\galaxy\api\importer.py", line 34, in _import_element
    element = await self._get(id_, context_)
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\plugin.py", line 408, in get_local_size
    return await self._local_client.get_game_size_in_bytes(title_id)
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\local.py", line 65, in get_game_size_in_bytes
    if path[:1] != '"':
TypeError: 'NoneType' object is not subscriptable
```

Edit:
Nope, I have found other errors:

```
2020-12-11 10:33:07,570 - root - DEBUG - Checking for new games...
2020-12-11 10:33:07,570 - root - DEBUG - Checking local game statuses...
2020-12-11 10:33:07,824 - root - DEBUG - ROCKSTAR_SC_TAG_DATA: ***
2020-12-11 10:33:07,825 - root - DEBUG - ROCKSTAR_ONLINE_GAME: Found played game gta5!
2020-12-11 10:33:07,825 - root - DEBUG - ROCKSTAR_ONLINE_GAME: Found played game rdr2!
2020-12-11 10:33:07,826 - root - DEBUG - ROCKSTAR_LOG_LOCATION: Checking the file ***...
2020-12-11 10:33:07,830 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID rdr2_rdo is owned!
2020-12-11 10:33:07,830 - root - WARNING - ROCKSTAR_UNPLAYED_GAME: The game with title ID rdr2_rdo is owned, but it has never been played!
2020-12-11 10:33:07,831 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID rdr2 is owned!
2020-12-11 10:33:07,831 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID gtasa is owned!
2020-12-11 10:33:07,831 - root - WARNING - ROCKSTAR_UNPLAYED_GAME: The game with title ID gtasa is owned, but it has never been played!
2020-12-11 10:33:07,832 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID rdr2_sp is owned!
2020-12-11 10:33:07,833 - root - WARNING - ROCKSTAR_UNPLAYED_GAME: The game with title ID rdr2_sp is owned, but it has never been played!
2020-12-11 10:33:07,833 - root - DEBUG - ROCKSTAR_LOG_GAME: The game with title ID rdr2_sp_rg is owned!
2020-12-11 10:33:07,833 - root - WARNING - ROCKSTAR_UNPLAYED_GAME: The game with title ID rdr2_sp_rg is owned, but it has never been played!
2020-12-11 10:33:07,834 - root - DEBUG - ROCKSTAR_ADD_GAME: Adding gta5 to owned games cache...
2020-12-11 10:33:07,834 - root - DEBUG - ROCKSTAR_ADD_GAME: Adding rdr2 to owned games cache...
2020-12-11 10:33:07,835 - root - ERROR - Task exception was never retrieved
future: <Task finished coro=<RockstarPlugin.check_for_new_games() done, defined at C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\plugin.py:595> exception=KeyError('rdr2_rdo')>
Traceback (most recent call last):
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\plugin.py", line 607, in check_for_new_games
    await self.get_owned_games(owned_title_ids, online_check_success)
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\plugin.py", line 398, in get_owned_games
    game = self.create_game_from_title_id(title_id)
  File "C:\Users\ekema\AppData\Local\GOG.com\Galaxy\plugins\installed\rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe\plugin.py", line 690, in create_game_from_title_id
    return Game(str(self.games_cache[title_id]["rosTitleId"]), self.games_cache[title_id]["friendlyName"], None,
KeyError: 'rdr2_rdo'
```

**Comment by fl4shback** [comment]
Hi!
Latest version is 0.5.9.
You can grab the built version here: https://github.com/FriendsOfGalaxy/galaxy-integration-rockstar/releases/tag/0.5.9

Should fix the issue that is in your log
