### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by sbpowar** [tylerbrawl/Galaxy-Plugin-Rockstar#143]

**Comment by tylerbrawl** [comment]
Um... Could you please be more descriptive? The plugin still seems to connect fine to the Rockstar Games Social Club for me, anyways. Do you have a log file generated by the plugin which you could submit here?

**Comment by sbpowar** [comment]
> Um... Could you please be more descriptive? The plugin still seems to connect fine to the Rockstar Games Social Club for me, anyways. Do you have a log file generated by the plugin which you could submit here?

Sorry, none of my games show up in GOG's library after connecting the plugin, this wasn't an issue earlier.
Where do I find the log file?

**Comment by tylerbrawl** [comment]
On Windows, you can find the log file at `C:\ProgramData\GOG.com\Galaxy\logs`. (I am unfamiliar myself with the location for the Mac OS version of Galaxy 2.0.) Within this directory, look for the file beginning with `plugin-rockstar`, and choose the latest log file (i.e., the one that ends in `.log` and not `.log.1`, `.log.2`, etc.).

In the event that we need it later, Rockstar's launcher also generates log files at `%USERPROFILE%\Documents\Rockstar Games\Launcher\launcher.log`.

**Comment by sbpowar** [comment]
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/7763561/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)
[launcher.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/7763566/launcher.log)

**Comment by skrollme** [comment]
Same problem for me. Just added the rockstar-plugin to _GOG Galaxy 2.0.45 (27)_ on _MacOS 12.1_ on a M1 MacBook and no games  from show up.

I also attached the plugin's log. Rockstar Launcher itself is not installed, so I have no launcher.log
[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/7781621/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)

**Comment by tylerbrawl** [comment]
First, I want to mention that I'm grateful for both of you being so patient. I have as of late been working on other project far outside of this plugin. With that said, I'll try and clear up any confusion for both of you.

@sbpowar - Thanks for including your Rockstar Games Launcher (RGL) log file. I see now that this happens because these games are not actually owned on the RGL; rather, they appear to be owned on other platforms. The plugin has no way to know which platforms you actually own these games on, so if they aren't owned on the RGL, then they won't be reported.

The log files seem to imply that you purchased these games on the Epic Games Store. They should show up under that store's plugin fine. However, because the games aren't owned on the RGL, they don't show up.

@skrollme - Your case is actually quite different from this issue. Since you use MacOS, you wouldn't be able to install the RGL. So, the plugin is actually supposed to report the list of played games. However, from the log file you provided, it appears that some error is preventing this from happening. It doesn't appear to happen on my system, however. I'll have to look into this later.

**Comment by sbpowar** [comment]
Thanks, but the plugin was working correctly a few months ago. I could see GTA V for RGL and all of my achievements.

**Comment by skrollme** [comment]
No hurry, @tylerbrawl . Just wanted to add some more debugging-information. Did not expect, that it is another problem :D

**Comment by Vincentqyx** [comment]
I am having the same problem. I have purchased the games through Rockstar and they are appearing in the Rockstar Launcher, but none of the games are appearing in GOG Galaxy with the Rockstar plugin installed. Attached are the logs for Rockstar launcher and the GOG Galaxy log.

[launcher.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/7797650/launcher.log)

[plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log](https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/files/7797651/plugin-rockstar-774732b5-69c4-405c-b6c9-92cd55740cfe.log)

**Comment by tylerbrawl** [comment]
@Vincentqyx - This problem was caused by the plugin not recognizing the GTA Definitive Trilogy. I have pushed an update to the `fog_release` branch (#146) which should fix your issue. It may take some time before the update gets downloaded automatically to your Galaxy 2.0 client.

When the update does arrive, I would appreciate if others could see if they are still having issues.

**Comment by skrollme** [comment]
The GOG client still does not want to update the plugin :D I already tried to delete the downloaded plugin-code but I keeps downloading the 0.5.13. But I will keep trying...

**Comment by skrollme** [comment]
The plugin stays on 0.5.13. I also reinstalled GOG, but I do not get a newer version. Also the problem for which I came here is also still present:

```
2022-01-23 14:31:57,754 - root - DEBUG - ROCKSTAR_SC_REFRESH_SUCCESS: The Social Club user has been successfully re-authenticated!
2022-01-23 14:31:58,167 - root - ERROR - ROCKSTAR_PLAYED_GAMES_ERROR: The request to scrape the user's played games resulted in this exception: TypeError('Cannot serialize non-str key None')
Traceback (most recent call last):
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/http_client.py", line 379, in get_played_games
    resp_json = await self._get_google_tag_data()
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/http_client.py", line 373, in _get_google_tag_data
    resp = await self._current_session.get(url, headers=headers)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/client.py", line 542, in _request
    resp = await req.send(conn)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/client_reqrep.py", line 668, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/http_writer.py", line 118, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 137, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/http_client.py", line 398, in get_played_games
    return await self.get_played_games(callback=True)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/http_client.py", line 379, in get_played_games
    resp_json = await self._get_google_tag_data()
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/http_client.py", line 373, in _get_google_tag_data
    resp = await self._current_session.get(url, headers=headers)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/client.py", line 542, in _request
    resp = await req.send(conn)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/client_reqrep.py", line 668, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/skroll/Library/Application Support/GOG.com/Galaxy/plugins/installed/rockstar_774732b5-69c4-405c-b6c9-92cd55740cfe/aiohttp/http_writer.py", line 118, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 137, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key None
2022-01-23 14:31:58,170 - root - ERROR - ROCKSTAR_PLAYED_GAMES_ERROR: The exception TypeError('Cannot serialize non-str key None') was thrown when attempting to get the user's played games online. Falling back to log file check...
```
